### ISSUE TITLE
Error: Nexthop has invalid gateway - Webui not accessible

### ISSUE THREAD

**Issue by D1s0rdu8** [DyonR/docker-qbittorrentvpn#127]
When using this config on my 192.168.0.30 host:

```
networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  default:
    driver: bridge
		
services:
  qbittorrent:
    image: dyonr/qbittorrentvpn:dev
    container_name: qbittorrent
    restart: always
    privileged: true
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.9
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "8112:8080"
      - "8999:8999"
      - "8999:8999/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/qbittorrent:/config
      - $DOCKERDIR/appdata/qbittorrent/tempdl:/downloads
      - $DATADIR/torrent:/torrent
    environment:
      VPN_ENABLED: "yes"
      VPN_TYPE: "openvpn"
      VPN_USERNAME: "***"
      VPN_PASSWORD: "***"
      LAN_NETWORK: "192.168.0.0/24"
      NAME_SERVERS: "1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4"
      ADDITIONAL_PORTS: "8112"
      INSTALL_PYTHON3: "yes"
```

give me the error:
```
[INFO] Docker network defined as 192.168.90.0/24
[INFO] Adding 192.168.0.0/24 as route via docker eth0
Error: Nexthop has invalid gateway.
```

Result : I can't access webui http://192.168.0.30:8112 from my local network 192.168.0.0/24

Solution is to manually add this route:
```
sudo docker exec -it qbittorrent bash
ip route add 192.168.0.0/24 via 192.168.90.1 dev eth0
```

Not sure if I have a special config or if this can be solved somehow in iptables.sh
