### ISSUE TITLE
qbittorrent runs as root

### ISSUE THREAD

**Issue by sebbe662** [DyonR/docker-qbittorrentvpn#171]
i am having an issue were no matter what puid and pgid i use qBitTorrent still downloads everything as root.

**Comment by DyonR** [comment]
What makes you think it runs as root?  
Could you perhaps share the log files?
If you open the console of the container and run `ps -o user= -p $(pgrep htop)`, what is the output?  
Example output: `qbittorrent`
In the console, after running the command above, could you also run `su qbittorrent` and then run `id` and add the output of that?  
Example output: `uid=1000(qbittorrent) gid=100(users) groups=100(users)`

**Comment by sebbe662** [comment]
im sorry, i should have specified that i am a bit lost on how containers and linux syntax work. i can enter the docker using ```docker exec -it qbittorrentvpn bash``` but i cant run ```ps -o user= -p $(pgrep htop)``` in the docker exec. (probably because of inexperience) it errors out saying command not found.

however, the big issue is that all the torrent it download is owned by root which i don't know how to change

![Screenshot 2023-04-02 165844](https://user-images.githubusercontent.com/77643776/229361051-8f47ce7a-73c8-4381-8630-de1e4f9c241a.png)

**Comment by DyonR** [comment]
Oh my bad, I used `htop` in my local machine as a test.  The proper command would be;  
`ps -o user= -p $(pgrep qbittorrent-nox)`  
  
When entering a container using `docker exec -it qbittorrentvpn bash`, that does indeed make you enter as the root user.  

The proper command to enter this container as `qbittorrent`-user instead of `root` would be `docker exec -it --user qbittorrent qbittorrentvpn /bin/bash`  
  
With Docker containers, it is normal to have root access, this doesn't mean that it has root access to your system, but only root access to operating system running in the docker.

**Comment by sebbe662** [comment]
this is the output i get when i did as you asked, tho it shows that qbittorrent is running as root.
![Screenshot 2023-04-02 170858](https://user-images.githubusercontent.com/77643776/229362092-cc9c0c63-908e-4dd9-801f-85f3c7ade2ea.png)

i have confirmation of this by looking at the content of the torrents that i am downloading.
![Screenshot 2023-04-02 171039](https://user-images.githubusercontent.com/77643776/229362127-1bf900b0-a274-4a7b-a858-1a5900e8c466.png)


is there any way to change the user?

here is the docker-compose that i am running as well.
```version: '2.4'
services:
  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Stockholm
      - HEALTH_CHECK_DISABLE=true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./config:/config
      - /mnt:/mnt
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.0.0/24,fd42:42:42::3/128
    ports:
      - 8080:8080
```

**Comment by DyonR** [comment]
On your Docker server/host, can you run `docker logs qbittorrentvpn` and upload that log to [Pastebin](https://pastebin.com/)?  
The log files don't really have any personal information in them, it does however show your VPN ip.
I don't see anything directly wrong with the docker-compose. 
One minor thing though, in your compose file you have two `environment` sections, these could be merged intro one:  
```
services:
  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Stockholm
      - HEALTH_CHECK_DISABLE=true
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.0.0/24,fd42:42:42::3/128
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./config:/config
      - /mnt:/mnt
    ports:
      - 8080:8080
```
