### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by hkhiro** [DyonR/docker-qbittorrentvpn#183]
Managed to get the container up and running and console can access the vpn network and do dns searches etc. but now having trouble getting the qbittorrent webui to actually work with the vpn. Think its just a noobie thing. I have created this compose file. Wondering if / how to add the cap-add and systemctl bits to it 

```dockerfile
services:
  torrent:
    image: dyonr/qbittorrentvpn:latest
    privileged: true
    network_mode: bridge
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    container_name: dyonr_torrent
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - VERSION=docker
      - VPN_ENABLED=yes
      - VPN_TYPE=openvpn
      - LAN_NETWORK=192.168.50.0/24
      - VPN_USERNAME=uuuuu 
      - VPN_PASSWORD=ppppp
      - HEALTH_CHECK_AMOUNT=10
      - ENABLE_SSL=1
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - UMASK=002
      - HEALTH_CHECK_HOST=one.one.one.one
      - HEALTH_CHECK_INTERVAL=5
      - HEALTH_CHECK_SILENT=1
      - INSTALL_PYTHON3=no
    volumes:
      - /home/Docker/TorrentDyonR:/config
      - /home/Downloads:/downloads
    restart: unless-stopped
``` 

so i can access the webuit and the console can do dns lookups. The problem is I cannot add plugins using any method and when I manually add a torrent nothing is happening. It just doesn't seem to want to work. Using chrome as well since I think Brave was not working with the login screen

**Comment by hkhiro** [comment]
still having issues with above compose file, but created another container using CLI which seems to have fired up. However, there is an issue now with Python - see logs 
[qbittorrent.log](https://github.com/DyonR/docker-qbittorrentvpn/files/11489331/qbittorrent.log)

found this related github issue - https://github.com/qbittorrent/search-plugins/issues/93

**Comment by gderf** [comment]
What are the contents of the container log file?

**Comment by hkhiro** [comment]
[dyonr portainer log](https://github.com/DyonR/docker-qbittorrentvpn/files/11509927/dyonr.portainer.log)

**Comment by gderf** [comment]
The container log isn't helping me.

Some questions/comments about your compose file:

Delete these:

privileged: true
network_mode: bridge

Add under image: dyonr/qbittorrentvpn:latest 
                  

cap_add:
    - NET_ADMIN

                        
Are the PUID and PGID you are using a real user and group that already exist on your system?

Delete this:
VERSION=docker

These are highly questionable to me, and you will very likely have to relocate these to a proper location:

volumes:
      - /home/Docker/TorrentDyonR:/config
      - /home/Downloads:/downloads

**/home** is generally owned by **root:users** and permissioned **drwxr-xr-x**  What this means is that only the root user can write there and the container will not be able to write there.

Do the **/home/Docker/TorrentDyonR** and **/home/Downloads** directories have any content in them and if so who owns it?

See if my suggestions help. I will paste my working compose file later if you ask to see it.

**Comment by cHunter789** [comment]
I can share my compose for Qnap NAS. For Qnap I have to set LEGACY_IPTABLES=yes. For OpenVPN the container need to have access to /dev/net/tun. In Qnap it's easy because container, in default, is running as a root (not so good) so I just add access to /dev/net/tun as a device. Others should check which group have permission for /dev/net/tun and set that group for used PUID/PGID in compose file (group_add) or better, create a new group for that [https://unix.stackexchange.com/questions/18215/which-user-group-can-use-the-tap-net-device ](https://unix.stackexchange.com/questions/18215/which-user-group-can-use-the-tap-net-device). I see the people are trying with chmod to /dev/net/tun at the host, but it's wrong approach. 

Below my compose for Qnap NAS (the port 8080 should be changed for those which use a default Qnap config).

Generally is crucial to set tun0 as interface to use in qbittorrent advanced config. Especially if something go wrong with iptables (you have to check logs to be sure there is no error in container). Using ipleak.net for verification highly recommended.

```
version: "3"
services:
  qbittorrent:
    image: dyonr/qbittorrentvpn:latest
    container_name: qbittorrent
    ports:
      - 8080:8080
    restart: "unless-stopped"
    mem_limit: 1G
    memswap_limit: 1G
    cap_add:
    - NET_ADMIN
    environment:
      - TZ=Europe/Berlin
      - VPN_ENABLED=yes
      - VPN_TYPE=openvpn
      - LAN_NETWORK=192.168.0.0/24
      - VPN_USERNAME=<username>
      - VPN_PASSWORD=<pass>
      - HEALTH_CHECK_AMOUNT=10
      - ENABLE_SSL=1
      - LEGACY_IPTABLES=yes
      - NAME_SERVERS=1.1.1.1
      - UMASK=002
      - HEALTH_CHECK_HOST=one.one.one.one
      - HEALTH_CHECK_INTERVAL=5
      - HEALTH_CHECK_SILENT=1
      - INSTALL_PYTHON3=yes
    volumes:
      - /share/Download/Cyberghostvpn/:/config
      - /share/Download/torrents:/downloads
    devices:
      - /dev/net/tun

 
```
