### ISSUE TITLE
Can I use this image to route other services through the VPN? in a docker-compose

### ISSUE THREAD

**Issue by carlos-algms** [DyonR/docker-qbittorrentvpn#189]
I want to use the VPN inside your image for other services in the same docker-compose file.

Would that be possible? 

```yaml
services:
  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    .....

  whatever_arr:
    .....
    network_mode: "service:qbittorrentvpn" # <<< here
```

thanks.
