### ISSUE TITLE
WebUI port is only accessible from the host and not on the LAN

### ISSUE THREAD

**Issue by francois-pasquier** [DyonR/docker-qbittorrentvpn#64]
Hi, I saw some issues similar to mine. I am not sure if the issue is exactly the same though.

My issue is that I can access the WebUI just fine via traefik and also from the host itself or from the container but if I try to access it from an other machine on the network `curl QBITTORRENT_IP:8081` will timeout.

```yml
  qbittorrent:
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1001
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.0.0/24
      - ADDITIONAL_PORTS=8081,8999
      - HEALTH_CHECK_HOST=one.one.one.one
      - HEALTH_CHECK_SILENT=1
    image: dyonr/qbittorrentvpn:rc_2_0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.whatever.com`)"
      - "traefik.http.routers.qbittorrent.tls.certresolver=le"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8081"
    networks:
      - default
    ports:
      - 8081:8081
      - 8999:8999
    privileged: true
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./etc/qbittorrent:/config
```

Is there anything I can try?
Is it a known issue?
